#!/bin/bash

echo "🔍 서버에서 실행할 상태 확인 명령어들"
echo "====================================="
echo ""
echo "1️⃣ 기존 Node.js 프로세스 확인:"
echo "ps aux | grep node"
echo ""
echo "2️⃣ 포트 5001 사용 중인지 확인:"
echo "sudo netstat -tlnp | grep :5001"
echo ""
echo "3️⃣ 기존 서버 로그 확인:"
echo "tail -20 /opt/minecraft2d/backend/minecraft2d.log"
echo ""
echo "4️⃣ 기존 서버 종료 후 새 서버 시작:"
echo "kill 39293  # 기존 서버 종료"
echo "cd /opt/minecraft2d/backend"
echo "nohup node server.js > server.log 2>&1 &"
echo ""
echo "5️⃣ 새 서버 로그 확인:"
echo "tail -f server.log"