#!/bin/bash

echo "🔧 서버에서 실행할 서비스 생성 명령어들"
echo "========================================"
echo ""
echo "1️⃣ systemd 서비스 파일 생성:"
echo "sudo tee /etc/systemd/system/minecraft2d.service > /dev/null << 'EOF'"
echo "[Unit]"
echo "Description=Minecraft 2D Game Server"
echo "After=network.target"
echo ""
echo "[Service]"
echo "Type=simple"
echo "User=ubuntu"
echo "WorkingDirectory=/opt/minecraft2d/backend"
echo "ExecStart=/usr/bin/node server.js"
echo "Restart=always"
echo "RestartSec=10"
echo "Environment=NODE_ENV=production"
echo "Environment=PORT=5001"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""
echo "2️⃣ 서비스 활성화 및 시작:"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable minecraft2d"
echo "sudo systemctl start minecraft2d"
echo ""
echo "3️⃣ 상태 확인:"
echo "sudo systemctl status minecraft2d"
echo ""
echo "4️⃣ 로그 확인:"
echo "sudo journalctl -u minecraft2d -f"