#!/bin/bash

echo "🔍 클라이언트-서버 연결 디버깅 명령어들"
echo "========================================"
echo ""
echo "1️⃣ 서버에서 맵 데이터 전송 로그 확인:"
echo "cd /opt/minecraft2d/backend"
echo "grep -A5 -B5 'map-data\\|request-map' server.log"
echo ""
echo "2️⃣ Socket.io 연결 상세 로그:"
echo "grep -A3 -B3 'socket\\|connect\\|disconnect' server.log"
echo ""
echo "3️⃣ 실시간 로그 모니터링:"
echo "tail -f server.log"
echo ""
echo "4️⃣ 브라우저에서 확인할 것들:"
echo "- F12 개발자 도구 열기"
echo "- Console 탭에서 다음 로그들 찾기:"
echo "  * '🔗 서버 연결 시도:'"
echo "  * '✅ 서버 연결 성공:'"
echo "  * '🗺️ 맵 데이터 요청'"
echo "  * '🗺️ 맵 데이터 수신:'"
echo ""
echo "5️⃣ Network 탭에서 확인:"
echo "- socket.io 요청들이 있는지"
echo "- WebSocket 연결 상태"
echo ""
echo "6️⃣ 문제 해결을 위한 서버 재시작:"
echo "kill \$(ps aux | grep 'node server.js' | grep -v grep | awk '{print \$2}')"
echo "sleep 2"
echo "nohup node server.js > server.log 2>&1 &"