#!/bin/bash

echo "🔧 채팅 기능 수정사항 배포 스크립트"
echo "===================================="
echo ""
echo "서버에서 실행할 명령어들:"
echo ""
echo "1️⃣ 최신 코드 받기:"
echo "cd /opt/minecraft2d"
echo "git pull origin oauth-fix"
echo ""
echo "2️⃣ 프론트엔드 재빌드:"
echo "cd Front"
echo "rm -rf build"
echo "npm run build"
echo ""
echo "3️⃣ 서버 재시작:"
echo "cd ../backend"
echo "pkill -f node"
echo "sleep 3"
echo "nohup node server.js > server.log 2>&1 &"
echo ""
echo "4️⃣ 서버 상태 확인:"
echo "ps aux | grep node"
echo ""
echo "✅ 완료 후 https://minecrafton.store 에서 테스트"
echo "   - Enter 키로 채팅창 열기"
echo "   - 메시지 입력 후 Enter로 전송"
echo "   - ESC 키로 채팅창 닫기"