#!/bin/bash

echo "🚀 서버에서 실행할 배포 명령어들"
echo "=================================="
echo ""
echo "1️⃣ 서버에 SSH 접속:"
echo "ssh ubuntu@minecrafton.store"
echo ""
echo "2️⃣ 프로젝트 디렉토리로 이동:"
echo "cd /opt/minecraft2d"
echo ""
echo "3️⃣ 최신 코드 받기:"
echo "git fetch origin"
echo "git checkout oauth-fix"
echo "git pull origin oauth-fix"
echo ""
echo "4️⃣ 프론트엔드 빌드:"
echo "cd frontend"
echo "npm run build"
echo ""
echo "5️⃣ 서비스 재시작:"
echo "sudo systemctl restart minecraft2d"
echo "sudo systemctl restart nginx"
echo ""
echo "6️⃣ 상태 확인:"
echo "sudo systemctl status minecraft2d"
echo "sudo systemctl status nginx"
echo ""
echo "✅ 완료 후 https://minecrafton.store 에서 테스트"
echo ""
echo "🔍 문제 해결됐는지 확인 방법:"
echo "1. Google 로그인 시도 (실패시켜도 됨)"
echo "2. 새로고침 (F5)"
echo "3. 이제 '맵 로딩 중...' 대신 로그인 화면이 나와야 함"